arm_stand:
  # Publish all joint states
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50
  # Position Controllers
  joint_base_mid_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_base_mid
    pid: {p: 100.0, i: 0.01, d: 10.0}
  joint_mid_top_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_mid_top
    pid: {p: 100.0, i: 0.01, d: 20.0}
  joint_top_fore_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_top_fore
    pid: {p: 100.0, i: 0.01, d: 20.0}
  #Hand_controllers
  hand_index_joint_controller: 
    type: effort_controllers/JointPositionController
    joint: hand_index_joint
    pid: {p: 50,  d: 0.1,  i: 0.1, i_clamp: 1}
  hand_thumb_joint_controller:
    type: effort_controllers/JointPositionController
    joint: hand_thumb_joint
    pid: {p: 50,  d: 0.1,  i: 0.1, i_clamp: 1}
  hand_mrl_joint_controller:
    type: effort_controllers/JointPositionController
    joint: hand_mrl_joint
    pid: {p: 50,  d: 0.1,  i: 0.1, i_clamp: 1}   
  hand_index_abd_joint_controller:
    type: effort_controllers/JointPositionController
    joint: hand_index_abd_joint
    pid: {p: 50,  d: 0.1,  i: 0.1, i_clamp: 1}
  hand_index_virtual_1_joint_controller:
    type: effort_controllers/JointPositionController
    joint: hand_index_virtual_1_joint
    pid: {p: 50,  d: 0.1,  i: 0.1, i_clamp: 1}
  hand_index_virtual_2_joint_controller:
    type: effort_controllers/JointPositionController
    joint: hand_index_virtual_2_joint
    pid: {p: 50,  d: 0.1,  i: 0.1, i_clamp: 1}
  hand_index_virtual_3_joint_controller:
    type: effort_controllers/JointPositionController
    joint: hand_index_virtual_3_joint
    pid: {p: 50,  d: 0.1,  i: 0.1, i_clamp: 1}
  hand_index_flex_1_joint_controller:
    type: effort_controllers/JointPositionController
    joint: hand_index_flex_1_joint
    pid: {p: 50,  d: 0.1,  i: 0.1, i_clamp: 1}
  hand_index_flex_2_joint_controller:
    type: effort_controllers/JointPositionController
    joint: hand_index_flex_2_joint
    pid: {p: 50,  d: 0.1,  i: 0.1, i_clamp: 1}
  hand_index_flex_3_joint_controller:
    type: effort_controllers/JointPositionController
    joint: hand_index_flex_3_joint
    pid: {p: 50,  d: 0.1,  i: 0.1, i_clamp: 1}
  hand_little_abd_joint_controller:
    type: effort_controllers/JointPositionController
    joint: hand_little_abd_joint
    pid: {p: 50,  d: 0.1,  i: 0.1, i_clamp: 1}
  hand_little_virtual_1_joint_controller:
    type: effort_controllers/JointPositionController
    joint: hand_little_virtual_1_joint
    pid: {p: 50,  d: 0.1,  i: 0.1, i_clamp: 1}
  hand_little_virtual_2_joint_controller:
    type: effort_controllers/JointPositionController
    joint: hand_little_virtual_2_joint
    pid: {p: 50,  d: 0.1,  i: 0.1, i_clamp: 1}
  hand_little_virtual_3_joint_controller:
    type: effort_controllers/JointPositionController
    joint: hand_little_virtual_3_joint
    pid: {p: 50,  d: 0.1,  i: 0.1, i_clamp: 1}
  hand_little_flex_1_joint_controller:
    type: effort_controllers/JointPositionController
    joint: hand_little_flex_1_joint
    pid: {p: 50,  d: 0.1,  i: 0.1, i_clamp: 1}
  hand_little_flex_2_joint_controller:
    type: effort_controllers/JointPositionController
    joint: hand_little_flex_2_joint
    pid: {p: 50,  d: 0.1,  i: 0.1, i_clamp: 1}
  hand_little_flex_3_joint_controller:
    type: effort_controllers/JointPositionController
    joint: hand_little_flex_3_joint
    pid: {p: 50,  d: 0.1,  i: 0.1, i_clamp: 1}    
  hand_middle_abd_joint_controller:
    type: effort_controllers/JointPositionController
    joint: hand_middle_abd_joint
    pid: {p: 50,  d: 0.1,  i: 0.1, i_clamp: 1}
  hand_middle_virtual_1_joint_controller:
    type: effort_controllers/JointPositionController
    joint: hand_middle_virtual_1_joint
    pid: {p: 50,  d: 0.1,  i: 0.1, i_clamp: 1}
  hand_middle_virtual_2_joint_controller:
    type: effort_controllers/JointPositionController
    joint: hand_middle_virtual_2_joint
    pid: {p: 50,  d: 0.1,  i: 0.1, i_clamp: 1}
  hand_middle_virtual_3_joint_controller:
    type: effort_controllers/JointPositionController
    joint: hand_middle_virtual_3_joint
    pid: {p: 50,  d: 0.1,  i: 0.1, i_clamp: 1}
  hand_middle_flex_1_joint_controller:
    type: effort_controllers/JointPositionController
    joint: hand_middle_flex_1_joint
    pid: {p: 50,  d: 0.1,  i: 0.1, i_clamp: 1}
  hand_middle_flex_2_joint_controller:
    type: effort_controllers/JointPositionController
    joint: hand_middle_flex_2_joint
    pid: {p: 50,  d: 0.1,  i: 0.1, i_clamp: 1}
  hand_middle_flex_3_joint_controller:
    type: effort_controllers/JointPositionController
    joint: hand_middle_flex_3_joint
    pid: {p: 50,  d: 0.1,  i: 0.1, i_clamp: 1}    
  hand_ring_abd_joint_controller:
    type: effort_controllers/JointPositionController
    joint: hand_ring_abd_joint
    pid: {p: 50,  d: 0.1,  i: 0.1, i_clamp: 1}
  hand_ring_virtual_1_joint_controller:
    type: effort_controllers/JointPositionController
    joint: hand_ring_virtual_1_joint
    pid: {p: 50,  d: 0.1,  i: 0.1, i_clamp: 1}
  hand_ring_virtual_2_joint_controller:
    type: effort_controllers/JointPositionController
    joint: hand_ring_virtual_2_joint
    pid: {p: 50,  d: 0.1,  i: 0.1, i_clamp: 1}
  hand_ring_virtual_3_joint_controller:
    type: effort_controllers/JointPositionController
    joint: hand_ring_virtual_3_joint
    pid: {p: 50,  d: 0.1,  i: 0.1, i_clamp: 1}
  hand_ring_flex_1_joint_controller:
    type: effort_controllers/JointPositionController
    joint: hand_ring_flex_1_joint
    pid: {p: 50,  d: 0.1,  i: 0.1, i_clamp: 1}
  hand_ring_flex_2_joint_controller:
    type: effort_controllers/JointPositionController
    joint: hand_ring_flex_2_joint
    pid: {p: 50,  d: 0.1,  i: 0.1, i_clamp: 1}
  hand_ring_flex_3_joint_controller:
    type: effort_controllers/JointPositionController
    joint: hand_ring_flex_3_joint
    pid: {p: 50,  d: 0.1,  i: 0.1, i_clamp: 1}  
  hand_thumb_abd_joint_controller:
    type: effort_controllers/JointPositionController
    joint: hand_thumb_abd_joint
    pid: {p: 50,  d: 0.1,  i: 0.1, i_clamp: 1}
  hand_thumb_virtual_1_joint_controller:
    type: effort_controllers/JointPositionController
    joint: hand_thumb_virtual_1_joint
    pid: {p: 50,  d: 0.1,  i: 0.1, i_clamp: 1}
  hand_thumb_virtual_2_joint_controller:
    type: effort_controllers/JointPositionController
    joint: hand_thumb_virtual_2_joint
    pid: {p: 50,  d: 0.1,  i: 0.1, i_clamp: 1}
  #NOT FOUND IN HARDWARE INTERFACE EFFORT JOINT CONTROLLER
#  hand_thumb_virtual_3_joint_controller:
#    type: effort_controllers/JointPositionController
#    joint: hand_thumb_virtual_3_joint
#    pid: {p: 50,  d: 0.1,  i: 0.1, i_clamp: 1}
  hand_thumb_flex_1_joint_controller:
    type: effort_controllers/JointPositionController
    joint: hand_thumb_flex_1_joint
    pid: {p: 50,  d: 0.1,  i: 0.1, i_clamp: 1}
  hand_thumb_flex_2_joint_controller:
    type: effort_controllers/JointPositionController
    joint: hand_thumb_flex_2_joint
    pid: {p: 50,  d: 0.1,  i: 0.1, i_clamp: 1}
  #NOT FOUND IN HARDWARE INTERFACE EFFORT JOINT CONTROLLER
#  hand_thumb_flex_3_joint_controller: 
#    type: effort_controllers/JointPositionController
#    joint: hand_thumb_flex_3_joint
#    pid: {p: 50,  d: 0.1,  i: 0.1, i_clamp: 1}
