arm_stand:
  # Publish all joint states
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50
  # Position Controllers
  joint_base_mid_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_base_mid
    pid: {p: 100.0, i: 0.01, d: 10.0}
  joint_mid_top_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_mid_top
    pid: {p: 100.0, i: 0.01, d: 20.0}
  joint_top_fore_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_top_fore
    pid: {p: 100.0, i: 0.01, d: 20.0}
  hand_controller:
    type: "position_controllers/JointTrajectoryController"
    joints:
      - hand_thumb_joint
      - hand_index_joint
      - hand_mrl_joint
  
    constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.75
      hand_thumb_joint:
        goal: &hand_goal_pos_constraint 0.3
      hand_index_joint:
        goal: 0.6
      hand_mrl_joint:
        goal: *hand_goal_pos_constraint
    stop_trajectory_duration: 0.0