gains:
  hand_index_joint: &finger_gains {p: 50,  d: 0.1,  i: 0.1, i_clamp: 1}
  hand_thumb_joint: *finger_gains
  hand_mrl_joint: *finger_gains
  hand_index_abd_joint: *finger_gains
  hand_index_virtual_1_joint: *finger_gains
  hand_index_virtual_2_joint: *finger_gains
  hand_index_virtual_3_joint: *finger_gains
  hand_index_flex_1_joint: *finger_gains
  hand_index_flex_2_joint: *finger_gains
  hand_index_flex_3_joint: *finger_gains
  hand_index_joint: *finger_gains
  hand_little_abd_joint: *finger_gains
  hand_little_virtual_1_joint: *finger_gains
  hand_little_virtual_2_joint: *finger_gains
  hand_little_virtual_3_joint: *finger_gains
  hand_little_flex_1_joint: *finger_gains
  hand_little_flex_2_joint: *finger_gains
  hand_little_flex_3_joint: *finger_gains
  hand_middle_abd_joint: *finger_gains
  hand_middle_virtual_1_joint: *finger_gains
  hand_middle_virtual_2_joint: *finger_gains
  hand_middle_virtual_3_joint: *finger_gains
  hand_middle_flex_1_joint: *finger_gains
  hand_middle_flex_2_joint: *finger_gains
  hand_middle_flex_3_joint: *finger_gains
  hand_ring_abd_joint: *finger_gains
  hand_ring_virtual_1_joint: *finger_gains
  hand_ring_virtual_2_joint: *finger_gains
  hand_ring_virtual_3_joint: *finger_gains
  hand_ring_flex_1_joint: *finger_gains
  hand_ring_flex_2_joint: *finger_gains
  hand_ring_flex_3_joint: *finger_gains
  hand_thumb_abd_joint: *finger_gains
  hand_thumb_virtual_1_joint: *finger_gains
  hand_thumb_virtual_2_joint: *finger_gains
  hand_thumb_virtual_3_joint: *finger_gains
  hand_thumb_flex_1_joint: *finger_gains
  hand_thumb_flex_2_joint: *finger_gains
  hand_thumb_flex_3_joint: *finger_gains
  hand_thumb_joint: *finger_gains
  hand_mrl_joint: *finger_gains