arm_stand:
  # Publish all joint states
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50
  # Position Controllers
  joint_base_mid_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_base_mid
    pid: {p: 100.0, i: 0.01, d: 10.0}
  joint_mid_top_psi_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_mid_top_psi
    pid: {p: 100.0, i: 0.01, d: 20.0}
  joint_mid_top_theta_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_mid_top_theta
    pid: {p: 100.0, i: 0.01, d: 20.0}
  joint_mid_top_phi_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_mid_top_phi
    pid: {p: 100.0, i: 0.01, d: 20.0}