# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: hand
  joint_model_group_pose: relaxed_hand
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - joint_base_mid
    - joint_mid_top
    - joint_top_fore
    - hand_index_abd_joint
    - hand_index_virtual_1_joint
    - hand_index_flex_1_joint
    - hand_index_virtual_2_joint
    - hand_index_flex_2_joint
    - hand_index_virtual_3_joint
    - hand_index_flex_3_joint
    - hand_index_joint
    - hand_little_abd_joint
    - hand_little_virtual_1_joint
    - hand_little_flex_1_joint
    - hand_little_virtual_2_joint
    - hand_little_flex_2_joint
    - hand_little_virtual_3_joint
    - hand_little_flex_3_joint
    - hand_middle_abd_joint
    - hand_middle_virtual_1_joint
    - hand_middle_flex_1_joint
    - hand_middle_virtual_2_joint
    - hand_middle_flex_2_joint
    - hand_middle_virtual_3_joint
    - hand_middle_flex_3_joint
    - hand_mrl_joint
    - hand_ring_abd_joint
    - hand_ring_virtual_1_joint
    - hand_ring_flex_1_joint
    - hand_ring_virtual_2_joint
    - hand_ring_flex_2_joint
    - hand_ring_virtual_3_joint
    - hand_ring_flex_3_joint
    - hand_thumb_abd_joint
    - hand_thumb_virtual_1_joint
    - hand_thumb_flex_1_joint
    - hand_thumb_virtual_2_joint
    - hand_thumb_flex_2_joint
    - hand_thumb_joint
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
arm_stand:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50
  hand_controller:
    type: effort_controllers/JointTrajectoryController
    joints:
      - hand_index_abd_joint
      - hand_index_virtual_1_joint
      - hand_index_flex_1_joint
      - hand_index_virtual_2_joint
      - hand_index_flex_2_joint
      - hand_index_virtual_3_joint
      - hand_index_flex_3_joint
      - hand_index_joint
      - hand_little_abd_joint
      - hand_little_virtual_1_joint
      - hand_little_flex_1_joint
      - hand_little_virtual_2_joint
      - hand_little_flex_2_joint
      - hand_little_virtual_3_joint
      - hand_little_flex_3_joint
      - hand_middle_abd_joint
      - hand_middle_virtual_1_joint
      - hand_middle_flex_1_joint
      - hand_middle_virtual_2_joint
      - hand_middle_flex_2_joint
      - hand_middle_virtual_3_joint
      - hand_middle_flex_3_joint
      - hand_mrl_joint
      - hand_ring_abd_joint
      - hand_ring_virtual_1_joint
      - hand_ring_flex_1_joint
      - hand_ring_virtual_2_joint
      - hand_ring_flex_2_joint
      - hand_ring_virtual_3_joint
      - hand_ring_flex_3_joint
      - hand_thumb_abd_joint
      - hand_thumb_virtual_1_joint
      - hand_thumb_flex_1_joint
      - hand_thumb_virtual_2_joint
      - hand_thumb_flex_2_joint
      - hand_thumb_joint
    gains:
      #hand_index_abd_joint: {p: 50,  d: 0.1,  i: 0.1, i_clamp: 1}
      hand_index_abd_joint: {p: &kp_default 50,  d: &kd_default 0.1, i: &ki_default 0, i_clamp: &ki__clamp_default 1}
      hand_index_virtual_1_joint: {p: *kp_default,  d: *kd_default , i: *ki_default, i_clamp: *ki__clamp_default}
      hand_index_flex_1_joint: {p: *kp_default,  d: *kd_default , i: *ki_default, i_clamp: *ki__clamp_default}
      hand_index_virtual_2_joint: {p: *kp_default,  d: *kd_default , i: *ki_default, i_clamp: *ki__clamp_default}
      hand_index_flex_2_joint: {p: *kp_default,  d: *kd_default , i: *ki_default, i_clamp: *ki__clamp_default}
      hand_index_virtual_3_joint: {p: *kp_default,  d: *kd_default , i: *ki_default, i_clamp: *ki__clamp_default}
      hand_index_flex_3_joint: {p: *kp_default,  d: *kd_default , i: *ki_default, i_clamp: *ki__clamp_default}
      hand_index_joint: {p: *kp_default,  d: *kd_default , i: *ki_default, i_clamp: *ki__clamp_default}
      hand_little_abd_joint: {p: *kp_default,  d: *kd_default , i: *ki_default, i_clamp: *ki__clamp_default}
      hand_little_virtual_1_joint: {p: *kp_default,  d: *kd_default , i: *ki_default, i_clamp: *ki__clamp_default}
      hand_little_flex_1_joint: {p: *kp_default,  d: *kd_default , i: *ki_default, i_clamp: *ki__clamp_default}
      hand_little_virtual_2_joint: {p: *kp_default,  d: *kd_default , i: *ki_default, i_clamp: *ki__clamp_default}
      hand_little_flex_2_joint: {p: *kp_default,  d: *kd_default , i: *ki_default, i_clamp: *ki__clamp_default}
      hand_little_virtual_3_joint: {p: *kp_default,  d: *kd_default , i: *ki_default, i_clamp: *ki__clamp_default}
      hand_little_flex_3_joint: {p: *kp_default,  d: *kd_default , i: *ki_default, i_clamp: *ki__clamp_default}
      hand_middle_abd_joint: {p: *kp_default,  d: *kd_default , i: *ki_default, i_clamp: *ki__clamp_default}
      hand_middle_virtual_1_joint: {p: *kp_default,  d: *kd_default , i: *ki_default, i_clamp: *ki__clamp_default}
      hand_middle_flex_1_joint: {p: *kp_default,  d: *kd_default , i: *ki_default, i_clamp: *ki__clamp_default}
      hand_middle_virtual_2_joint: {p: *kp_default,  d: *kd_default , i: *ki_default, i_clamp: *ki__clamp_default}
      hand_middle_flex_2_joint: {p: *kp_default,  d: *kd_default , i: *ki_default, i_clamp: *ki__clamp_default}
      hand_middle_virtual_3_joint: {p: *kp_default,  d: *kd_default , i: *ki_default, i_clamp: *ki__clamp_default}
      hand_middle_flex_3_joint: {p: *kp_default,  d: *kd_default , i: *ki_default, i_clamp: *ki__clamp_default}
      hand_mrl_joint: {p: *kp_default,  d: *kd_default , i: *ki_default, i_clamp: *ki__clamp_default}
      hand_ring_abd_joint: {p: *kp_default,  d: *kd_default , i: *ki_default, i_clamp: *ki__clamp_default}
      hand_ring_virtual_1_joint: {p: *kp_default,  d: *kd_default , i: *ki_default, i_clamp: *ki__clamp_default}
      hand_ring_flex_1_joint: {p: *kp_default,  d: *kd_default , i: *ki_default, i_clamp: *ki__clamp_default}
      hand_ring_virtual_2_joint: {p: *kp_default,  d: *kd_default , i: *ki_default, i_clamp: *ki__clamp_default}
      hand_ring_flex_2_joint: {p: *kp_default,  d: *kd_default , i: *ki_default, i_clamp: *ki__clamp_default}
      hand_ring_virtual_3_joint: {p: *kp_default,  d: *kd_default , i: *ki_default, i_clamp: *ki__clamp_default}
      hand_ring_flex_3_joint: {p: *kp_default,  d: *kd_default , i: *ki_default, i_clamp: *ki__clamp_default}
      hand_thumb_abd_joint: {p: *kp_default,  d: *kd_default , i: *ki_default, i_clamp: *ki__clamp_default}
      hand_thumb_virtual_1_joint: {p: *kp_default,  d: *kd_default , i: *ki_default, i_clamp: *ki__clamp_default}
      hand_thumb_flex_1_joint: {p: *kp_default,  d: *kd_default , i: *ki_default, i_clamp: *ki__clamp_default}
      hand_thumb_virtual_2_joint: {p: *kp_default,  d: *kd_default , i: *ki_default, i_clamp: *ki__clamp_default}
      hand_thumb_flex_2_joint: {p: *kp_default,  d: *kd_default , i: *ki_default, i_clamp: *ki__clamp_default}
      hand_thumb_joint: {p: *kp_default,  d: *kd_default , i: *ki_default, i_clamp: *ki__clamp_default}
      
    constraints:
      goal_time: &goal_time_constraint 4.0
      hand_index_abd_joint: 
        goal: &goal_pos_constraint 0
        #trajectory: &trajectory_pos_constraint 0
      hand_index_virtual_1_joint:
        goal: *goal_pos_constraint 
        #trajectory: *trajectory_pos_constraint
      hand_index_flex_1_joint: 
        goal: *goal_pos_constraint
        #trajectory: *trajectory_pos_constraint
      hand_index_virtual_2_joint: 
        goal: *goal_pos_constraint
        #trajectory: *trajectory_pos_constraint
      hand_index_flex_2_joint: 
        goal: *goal_pos_constraint
        #trajectory: *trajectory_pos_constraint
      hand_index_virtual_3_joint: 
        goal: *goal_pos_constraint
        #trajectory: *trajectory_pos_constraint
      hand_index_flex_3_joint: 
        goal: *goal_pos_constraint
        #trajectory: *trajectory_pos_constraint
      hand_index_joint: 
        goal: *goal_pos_constraint
        #trajectory: *trajectory_pos_constraint
      hand_little_abd_joint: 
        goal: *goal_pos_constraint
        #trajectory: *trajectory_pos_constraint
      hand_little_virtual_1_joint: 
        goal: *goal_pos_constraint
        #trajectory: *trajectory_pos_constraint
      hand_little_flex_1_joint: 
        goal: *goal_pos_constraint
        #trajectory: *trajectory_pos_constraint
      hand_little_virtual_2_joint: 
        goal: *goal_pos_constraint
        #trajectory: *trajectory_pos_constraint
      hand_little_flex_2_joint: 
        goal: *goal_pos_constraint
        #trajectory: *trajectory_pos_constraint
      hand_little_virtual_3_joint: 
        goal: *goal_pos_constraint
        #trajectory: *trajectory_pos_constraint
      hand_little_flex_3_joint: 
        goal: *goal_pos_constraint
        #trajectory: *trajectory_pos_constraint
      hand_middle_abd_joint:
        goal: *goal_pos_constraint
        #trajectory: *trajectory_pos_constraint
      hand_middle_virtual_1_joint: 
        goal: *goal_pos_constraint
        #trajectory: *trajectory_pos_constraint
      hand_middle_flex_1_joint: 
        goal: *goal_pos_constraint
        #trajectory: *trajectory_pos_constraint
      hand_middle_virtual_2_joint: 
        goal: *goal_pos_constraint
        #trajectory: *trajectory_pos_constraint
      hand_middle_flex_2_joint:
        goal: *goal_pos_constraint
        #trajectory: *trajectory_pos_constraint
      hand_middle_virtual_3_joint: 
        goal: *goal_pos_constraint
        #trajectory: *trajectory_pos_constraint
      hand_middle_flex_3_joint: 
        goal: *goal_pos_constraint
        #trajectory: *trajectory_pos_constraint
      hand_mrl_joint: 
        goal: *goal_pos_constraint
        #trajectory: *trajectory_pos_constraint
      hand_ring_abd_joint: 
        goal: *goal_pos_constraint
        #trajectory: *trajectory_pos_constraint
      hand_ring_virtual_1_joint:  
        goal: *goal_pos_constraint
        #trajectory: *trajectory_pos_constraint
      hand_ring_flex_1_joint: 
        goal: *goal_pos_constraint
        #trajectory: *trajectory_pos_constraint
      hand_ring_virtual_2_joint: 
        goal: *goal_pos_constraint
        #trajectory: *trajectory_pos_constraint
      hand_ring_flex_2_joint: 
        goal: *goal_pos_constraint
        #trajectory: *trajectory_pos_constraint
      hand_ring_virtual_3_joint: 
        goal: *goal_pos_constraint
        #trajectory: *trajectory_pos_constraint
      hand_ring_flex_3_joint: 
        goal: *goal_pos_constraint
        #trajectory: *trajectory_pos_constraint
      hand_thumb_abd_joint: 
        goal: *goal_pos_constraint
        #trajectory: *trajectory_pos_constraint
      hand_thumb_virtual_1_joint: 
        goal: *goal_pos_constraint
        #trajectory: *trajectory_pos_constraint
      hand_thumb_flex_1_joint: 
        goal: *goal_pos_constraint
        #trajectory: *trajectory_pos_constraint
      hand_thumb_virtual_2_joint: 
        goal: *goal_pos_constraint
        #trajectory: *trajectory_pos_constraint
      hand_thumb_flex_2_joint: 
        goal: *goal_pos_constraint
        #trajectory: *trajectory_pos_constraint
      hand_thumb_joint: 
        goal: *goal_pos_constraint
        #trajectory: *trajectory_pos_constraint

  arm_controller:
    type: effort_controllers/JointTrajectoryController
    joints:
      - joint_base_mid
      - joint_mid_top
      - joint_top_fore
    gains:
      #joint_base_mid: { p: 12000, d: 50, i: 0.0, i_clamp: 10000 }
      joint_base_mid: { p: 5000, d: 20, i: 0.01, i_clamp: 10000 }
      joint_mid_top: { p: 5000, d: 20, i: 0.01, i_clamp: 10000 }
      joint_top_fore: { p: 5000, d: 20, i: 0.01, i_clamp: 10000 }
    constraints:
            goal_time: 2.0
    state_publish_rate: 25
controller_list:
  - name: arm_stand/hand_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - hand_index_abd_joint
      - hand_index_virtual_1_joint
      - hand_index_flex_1_joint
      - hand_index_virtual_2_joint
      - hand_index_flex_2_joint
      - hand_index_virtual_3_joint
      - hand_index_flex_3_joint
      - hand_index_joint
      - hand_little_abd_joint
      - hand_little_virtual_1_joint
      - hand_little_flex_1_joint
      - hand_little_virtual_2_joint
      - hand_little_flex_2_joint
      - hand_little_virtual_3_joint
      - hand_little_flex_3_joint
      - hand_middle_abd_joint
      - hand_middle_virtual_1_joint
      - hand_middle_flex_1_joint
      - hand_middle_virtual_2_joint
      - hand_middle_flex_2_joint
      - hand_middle_virtual_3_joint
      - hand_middle_flex_3_joint
      - hand_mrl_joint
      - hand_ring_abd_joint
      - hand_ring_virtual_1_joint
      - hand_ring_flex_1_joint
      - hand_ring_virtual_2_joint
      - hand_ring_flex_2_joint
      - hand_ring_virtual_3_joint
      - hand_ring_flex_3_joint
      - hand_thumb_abd_joint
      - hand_thumb_virtual_1_joint
      - hand_thumb_flex_1_joint
      - hand_thumb_virtual_2_joint
      - hand_thumb_flex_2_joint
      - hand_thumb_joint
  - name: arm_stand/arm_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - joint_base_mid
      - joint_mid_top
      - joint_top_fore