# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: hand
  joint_model_group_pose: pinch
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - joint_base_mid
    - joint_mid_top
    - joint_top_fore
    - hand_index_abd_joint
    - hand_index_virtual_1_joint
    - hand_index_flex_1_joint
    - hand_index_virtual_2_joint
    - hand_index_flex_2_joint
    - hand_index_virtual_3_joint
    - hand_index_flex_3_joint
    - hand_index_joint
    - hand_little_abd_joint
    - hand_little_virtual_1_joint
    - hand_little_flex_1_joint
    - hand_little_virtual_2_joint
    - hand_little_flex_2_joint
    - hand_little_virtual_3_joint
    - hand_little_flex_3_joint
    - hand_middle_abd_joint
    - hand_middle_virtual_1_joint
    - hand_middle_flex_1_joint
    - hand_middle_virtual_2_joint
    - hand_middle_flex_2_joint
    - hand_middle_virtual_3_joint
    - hand_middle_flex_3_joint
    - hand_mrl_joint
    - hand_ring_abd_joint
    - hand_ring_virtual_1_joint
    - hand_ring_flex_1_joint
    - hand_ring_virtual_2_joint
    - hand_ring_flex_2_joint
    - hand_ring_virtual_3_joint
    - hand_ring_flex_3_joint
    - hand_thumb_abd_joint
    - hand_thumb_virtual_1_joint
    - hand_thumb_flex_1_joint
    - hand_thumb_virtual_2_joint
    - hand_thumb_flex_2_joint
    - hand_thumb_joint
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  - name: hand_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - hand_index_abd_joint
      - hand_index_virtual_1_joint
      - hand_index_flex_1_joint
      - hand_index_virtual_2_joint
      - hand_index_flex_2_joint
      - hand_index_virtual_3_joint
      - hand_index_flex_3_joint
      - hand_index_joint
      - hand_little_abd_joint
      - hand_little_virtual_1_joint
      - hand_little_flex_1_joint
      - hand_little_virtual_2_joint
      - hand_little_flex_2_joint
      - hand_little_virtual_3_joint
      - hand_little_flex_3_joint
      - hand_middle_abd_joint
      - hand_middle_virtual_1_joint
      - hand_middle_flex_1_joint
      - hand_middle_virtual_2_joint
      - hand_middle_flex_2_joint
      - hand_middle_virtual_3_joint
      - hand_middle_flex_3_joint
      - hand_mrl_joint
      - hand_ring_abd_joint
      - hand_ring_virtual_1_joint
      - hand_ring_flex_1_joint
      - hand_ring_virtual_2_joint
      - hand_ring_flex_2_joint
      - hand_ring_virtual_3_joint
      - hand_ring_flex_3_joint
      - hand_thumb_abd_joint
      - hand_thumb_virtual_1_joint
      - hand_thumb_flex_1_joint
      - hand_thumb_virtual_2_joint
      - hand_thumb_flex_2_joint
      - hand_thumb_joint
  - name: arm_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - joint_base_mid
      - joint_mid_top
      - joint_top_fore