<?xml version="1.0"?>
<!-- Revolute-Revolute Manipulator -->

<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="arm_stand">
  
  <gazebo reference='joint_mid_top'>
    <preserveFixedJoint>true</preserveFixedJoint>
  </gazebo>
  
  <gazebo reference='camera_joint'>
    <preserveFixedJoint>true</preserveFixedJoint>
  </gazebo>
  
  <!-- Constants for robot dimensions -->
  <xacro:property name="width" value="0.1" />
  <xacro:property name="height1" value="1" />
  <xacro:property name="height2" value="0.5" />
  <xacro:property name="height3" value="0.5" />
  <xacro:property name="axle_offset" value="0.05" />
  <xacro:property name="damp" value="0" />
  <xacro:property name="friction" value="0.1" />
  <xacro:property name="camera_link" value="0.05" /> 
  <!-- Size of square 'camera' box -->
  
  
  <!-- Import Rviz colors -->
  <xacro:include
      filename="$(find arm_description)/urdf/materials.urdf.xacro" />

  <!-- Default Inertial -->
  <xacro:macro name="default_inertial" params="z_value i_value mass">
    <inertial>
      <origin xyz="0 0 ${z_value}" rpy="0 0 0"/>
      <mass value="${mass}"/>
      <inertia ixx="${i_value}" ixy="0.0" ixz="0.0"
               iyy="${i_value}" iyz="0.0"
               izz="${i_value}" />
    </inertial>
  </xacro:macro>
  
  <!-- Importing End-Effector -->
  <!--Arguments-->
  <xacro:arg name="end_effector" default="pal-hey5"/> <!-- false, pal-gripper, pal-hey5, schunk-wsg-->
  <xacro:property name="end_effector" value="$(arg end_effector)" />
  <xacro:property name="end_effector_name"       value="${'hand' if end_effector == 'pal-hey5' else 'gripper'}"/>
  
  <!-- Include end effector -->
  <!--<xacro:include filename="$(find hey5_description)/urdf/gripper.xacro"/>-->
  <xacro:include filename="$(find tiago_description)/urdf/end_effector/end_effector.urdf.xacro" />
  <xacro:include filename="$(find tiago_description_calibration)/urdf/calibration/calibration_constants.urdf.xacro" />
  <xacro:tiago_end_effector name="${end_effector_name}" parent="top_link" type="${end_effector}" reflect="1"/>
  
  <!-- Include Gazebo tags -->
  <xacro:include filename="$(find arm_description)/gazebo/arm_stand_gazebo.urdf.xacro"/>
  
  <!--Arm Stand-->
   
  <link name="world"/>
  
  <joint name="fixed" type="fixed">
    <parent link="world"/>
    <child link="base_link"/>
  </joint>
  
  <!-- Base Link -->
  <link name="base_link">
    <visual>
      <origin xyz="0 0 ${height1/2}" rpy="0 0 0" />
      <geometry>
        <box size="${width} ${width} ${height1}" />
      </geometry>
      <material name="white"/>
    </visual>
    <collision>
      <origin xyz="0 0 ${height1/2}" rpy="0 0 0" />
      <geometry>
        <box size="${width} ${width} ${height1}" />
      </geometry>
    </collision>
    <xacro:default_inertial z_value="${height1/2}" i_value="1.0" mass="1"/>
  </link>
  
  <!-- Joint between Base Link and Middle Link -->
  <joint name="joint_base_mid" type="revolute">
    <parent link="base_link" />
    <child link="mid_link" />
    <origin xyz="0 ${width} ${height1 - axle_offset}" rpy="0 0 0"/>
    <axis xyz="0 1 0" />
    <dynamics damping="${damp}" friction = "${friction}" />
    <limit effort="100.0" velocity="0.5" lower="-3.14" upper="3.14"/>
  </joint>
  
  <transmission name="trans_base_mid">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="joint_base_mid">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor_base_mid">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>
  
  <!-- Middle Link -->
  <link name="mid_link">
    <visual>
      <origin xyz="0 0 ${height2/2 - axle_offset}" rpy="0 0 0" />
      <geometry>
        <box size="${width} ${width} ${height2}" />
      </geometry>
      <material name="green"/>
    </visual>
    <collision>
      <origin xyz="0 0 ${height2/2 - axle_offset}" rpy="0 0 0" />
      <geometry>
        <box size="${width} ${width} ${height2}" />
      </geometry>
    </collision>
    <xacro:default_inertial z_value="${height2/2 - axle_offset}" 
    i_value="1.0" mass="1"/>
  </link>
  
  <!-- Joint between Middle Link and Top Link 3DOF -->
  <joint name="joint_mid_top" type="fixed">
    <parent link="mid_link" />
    <child link="ball_link" />
    <origin xyz="0 ${width} ${height2 - axle_offset*2}" rpy="0 0 0"/>
    <!--<axis xyz="0 1 0" />
    <dynamics damping="${damp}" friction = "${friction}" />
    <limit effort="100.0" velocity="0.5" lower="-3.14" upper="3.14"/>-->
  </joint>
  <link name="ball_link">
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value=".00001"/>
      <inertia ixx="0.00001" ixy="0.0" ixz="0.0" iyy="0.00001"  iyz="0.0" izz ="0.00001"/>
    </inertial>
  </link>
  <joint name="joint_mid_top_psi" type="continuous" >
      <parent link="ball_link" />
      <child link="ball_link_psi_link" />
      <!--<limit effort="100.0" velocity="0.5" lower="-3.14" upper="3.14"/>-->
      <axis xyz="0 0 1" />
      <dynamics damping="${damp}" friction = "${friction}" />
  </joint>
  <transmission name="trans_mid_top_psi">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="joint_mid_top_psi">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor_mid_top_psi">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>  
  <link name="ball_link_psi_link" >
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value=".00001"/>
      <inertia ixx="0.00001" ixy="0.0" ixz="0.0" iyy="0.000011"  iyz="0.0" izz ="0.00001"/>
    </inertial>
  </link>
  <joint name="joint_mid_top_theta" type="continuous" >
      <parent link="ball_link_psi_link"/>
      <child link="ball_link_theta_link"/>
      <!--<limit effort="100.0" velocity="0.5" lower="-3.14" upper="3.14"/>-->
      <axis xyz="0 1 0" />
      <dynamics damping="${damp}" friction = "${friction}" />
  </joint>
  <transmission name="trans_mid_top_theta">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="joint_mid_top_theta">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor_mid_top_theta">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission> 
  <link name="ball_link_theta_link" >
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value=".00001"/>
      <inertia ixx="0.00001" ixy="0.0" ixz="0.0" iyy="0.00001"  iyz="0.0" izz ="0.00001"/>
    </inertial>
  </link>
  <joint name="joint_mid_top_phi" type="continuous" >
      <parent link="ball_link_theta_link"/>
      <child link="top_link"/>
      <axis xyz="1 0 0" />
      <!--<limit effort="100.0" velocity="0.5" lower="-3.14" upper="3.14"/>-->
      <dynamics damping="${damp}" friction = "${friction}" />
  </joint>
  <transmission name="trans_mid_top_phi">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="joint_mid_top_phi">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor_mid_top_phi">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission> 
    
  <!-- Top Link -->
  <link name="top_link">
    <visual>
      <origin xyz="0 0 ${height3/2 - axle_offset}" rpy="0 0 0" />
      <geometry>
        <box size="${width} ${width} ${height3}" />
      </geometry>
      <material name="red"/>
    </visual>
    <collision>
      <origin xyz="0 0 ${height3/2 - axle_offset}" rpy="0 0 0" />
      <geometry>
        <box size="${width} ${width} ${height3}" />
      </geometry>
    </collision>
    <xacro:default_inertial z_value="${height3/2 - axle_offset}"
      i_value="1.0" mass="1"/>
  </link>
  
  <joint name="camera_joint" type="fixed">
    <origin xyz="0 0 ${height2 - axle_offset*2}" rpy="0 1.57 -1.57"/>
    <parent link="top_link"/>
    <child link="camera_link"/>
    <dynamics damping="${damp}" friction = "${friction}" />
  </joint>

  <!-- Camera Link -->
  <link name="camera_link">
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${camera_link} ${camera_link} ${camera_link}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 ${camera_link + camera_link/2}" rpy="0 0 0"/>
      <geometry>
        <box size="${camera_link} ${camera_link} ${camera_link}"/>
      </geometry>
      <material name="white"/>
    </visual>

    <inertial>
      <mass value="1e-5" />
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6" />
    </inertial>
  </link>
  
  
 <!-- <joint name="hand_joint" type="revolute">
    <parent link="top_link"/>
    <child link="left_gripper"/>
    <origin xyz="0 0 ${height2 - axle_offset}" rpy="0 -1.57 0"/>
    <axis xyz="0 0 1"/>
    <limit effort="30.0" lower="-0.548" upper="0.0" velocity="0.1"/>
  </joint> -->
  
</robot>  

<!--
  This XML code defines a robot arm which has three links that are
0.1 meters deep and wide. The base_link is 2 meters tall, and the mid_link and top_link are both 1 meter tall. The origin of the base_link is at (0, 0, 1).
The reference frame of the box is 1 meter in the z direction above the reference frame of the link. This base_link is identified as the URDF root link and is the beginning of the kinematic chain for the
arm. The collision elements of each match their visual elements. Each inertial element indicates that each link weighs 1 kilogram and has the same basic inertia matrix values.

 The dynamics damping coefficient is set to 0.7 Nms/rad. This damping
is the amount of opposing force to any joint velocity, used to slow down the moving arms to a rest position. The <limit> tag is required for revolute joints. The limit effort is set to 1000.0 N-m for the maximum joint effort that can be commanded. The joint velocity is limited to a magnitude of 0.5 rad/s, with a damping effort applied when the joint is commanded beyond this limit. The upper and lower limits of the joint are set to pi radians and -pi radians, respectively.
-->